MISSION_BRIEFING = [
    "TOP SECRET DOCUMENT (VERY HIGH PRIORITY)",
    " ", 
    "To      : AGENT 47 (Cyber Division 7)", 
    "From    : Hacker Alliance", 
    "Target  : Neo-Capital City Sector",
    "Subject : Eradication Operation: Corrupt Syndicate (ORDAL)", 
    " ", 
    "MISSION STATUS: ACTIVE - SHADOW PROTOCOL", 
    " ", 
    "EXECUTION ORDERS:", 
    "1. Infiltrate and hack into the main servers of the city's corrupt elites.", 
    "2. Gather evidence of illicit transactions, money laundering, and 'Insider' (ORDAL) connections. A5-432", 
    "3. Bypass 50 layers of their digital asset protection firewalls. A7-675", 
    "4. Drain all corrupted funds and wipe their financial network across the city without a trace. A9-778", 
    " ", 
    "WARNING: YOU ARE OPERATING OUTSIDE THE SYSTEM!", 
    "IF CAUGHT, WE WILL DENY YOUR EXISTENCE.", 
    "FAILURE = THE CITY FALLS TO THE PARASITES.", 
    " ", 
    "Issued by: The Glitch (Master Hacker)", 
    "Created by: Dwi Bakti N Dev",
    "ID Card: A47-002",
    "[ ENCRYPTED SIGNATURE ] CODE: REVOLUTION_2"
]
MISSION_TIPS = [
    "TIP: Collect every access key before the exit will unlock.",
    "TIP: Contact with a patrol unit means instant termination.",
    "TIP: Traps and hazards hide in the corridors - move carefully.",
    "TIP: Reach the open door once all keys are secured.",
    "TIP: Each corrupt node destroyed brings freedom closer.",
    "TIP: Stay stealthy, stay alive, Agent 47.",
    "TIP: Press F5 anytime to save your infiltration progress.",
    "TIP: ORDAL's defenses grow stronger with every floor.",
    "TIP: Sound carries—walking is quieter than running.",
    "TIP: Security cameras have blind spots; learn the rotation.",
    "TIP: Do not rush into elevators; they are often rigged.",
    "TIP: Trust no terminal—the network might be trapped.",
    "TIP: Data logs often contain passwords for locked doors.",
    "TIP: Upgrade your rig when you find hidden caches.",
    "TIP: Shadows are your best friend; stay out of the light.",
    "TIP: Red lasers indicate a lethal security grid.",
    "TIP: Hack vending machines to create a noise distraction.",
    "TIP: The lobby is a trap—move fast through open areas.",
    "TIP: Read emails on terminals for critical intel.",
    "TIP: Look for ventilation shafts to bypass security gates.",
    "TIP: The ORDAL elites are watching—stay off the main path.",
    "TIP: Corruption spreads deeper as you ascend.",
    "TIP: Do not leave a digital footprint—delete your logs.",
    "TIP: Power surges can temporarily disable electronic locks.",
    "TIP: Study the guard patterns before making your move.",
    "TIP: Every floor has a unique override code.",
    "TIP: Trust your instincts more than the interface.",
    "TIP: If the alarm sounds, hide immediately and wait.",
    "TIP: Use furniture and environmental cover to break line-of-sight.",
    "TIP: Layouts change—never assume a path is safe twice.",
    "TIP: Don't trust the 'Help' menu—it may be monitored.",
    "TIP: Efficiency is key; don't waste time on empty rooms.",
    "TIP: Keep your battery charged; hacking drains power.",
    "TIP: Look for blueprints in file cabinets to reveal traps.",
    "TIP: The server room is the heart—protect yourself there.",
    "TIP: Some floors require a Master Key to fully unlock.",
    "TIP: Avoid contact with drones—they scan for identity.",
    "TIP: The higher you go, the more complex the firewalls.",
    "TIP: Check corners before advancing into new sectors.",
    "TIP: Silence is your weapon—avoid unnecessary combat.",
    "TIP: Junior clerks are often informants—avoid them.",
    "TIP: Sometimes the 'Exit' is a lure—check the area first.",
    "TIP: Use audio decoys to draw guards away from doors.",
    "TIP: If you see blue lasers, they are motion sensors.",
    "TIP: Recover energy by standing near secure power cores.",
    "TIP: Avoid the center hallway—it's high traffic.",
    "TIP: The resistance is counting on your speed.",
    "TIP: Don't let your connection time out during a hack.",
    "TIP: The ultimate truth is hidden on the top level.",
    "TIP: Finish the job, Agent 47. There is no fallback."
]